import type { Metadata } from "next";
import { Playfair_Display, Montserrat } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import AppProvider from "@/provider/AppProvider";
import AuthProvider from "@/provider/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import { ContexProvider } from "@/lib/AppContext";

// Google Fonts
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-montserrat",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Property Nexus",
  description: "Generated by create next app",
  icons: "/assets/fav.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${playfairDisplay.variable} antialiased`}
      >
        {/* NextTopLoader with gradient */}
        <NextTopLoader color="#0078B8" height={3} showSpinner={false} />
        <AuthProvider>
          <ContexProvider>
          <AppProvider>{children}</AppProvider>
          </ContexProvider>
           <Toaster position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
